services:
  postgres:
    image: 'postgres:16.1'
    environment:
      - 'POSTGRES_DB=germany_graph'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
    ports:
      - '5432:5432'
    volumes:
      - './src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql'